apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ad-generator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ad-generator-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70